# Generated by Django 3.1.7 on 2021-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210625_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnotification',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status1',
            field=models.CharField(blank=True, default='Pending', max_length=254, null=True),
        ),
    ]
