# Generated by Django 3.0.8 on 2021-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210807_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additiondetail',
            name='type_disability',
            field=models.IntegerField(choices=[(1, 'Vision Impairment'), (2, 'Deaf or hard of hearing'), (3, 'Mental health conditions'), (4, 'Intellectual disability'), (5, 'Acquired brain injury'), (6, 'Autism spectrum disorder'), (7, 'Physical disability')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='age_relaxation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='age_relaxation_code',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='arranged_by',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='arrangement_own_scribe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_join_civil',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='discharge_ex_serviceman',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='ex_Serviceman',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='join_civil',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='provide_exam_help',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scribe_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='service_inyears',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='suffering_cerebral_palsy',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
