# Generated by Django 3.0.8 on 2021-10-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20211004_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_year',
        ),
    ]
