# Generated by Django 3.0.8 on 2021-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_notice_notice_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
