# Generated by Django 3.0.8 on 2021-10-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20211004_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-upload_date']},
        ),
    ]
