# Generated by Django 3.0.8 on 2021-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20211004_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
