# Generated by Django 3.0.8 on 2021-10-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20211004_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-not_date']},
        ),
    ]
