# Generated by Django 3.0.8 on 2021-10-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20211004_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-upload_date']},
        ),
    ]
