AADHAR = ((0, "Yes"), (1, "No"))

HIGHEST_QUALIFICATION = ((1, "Matric/High School"), (2, "Intermediate/Higher Secondary/12thStandard"), (3, "Certificate"), (4, "Diploma"), (5, "BA"), (6, "BA (Hons.)"), (7, "B. Com."), (8, "B.Com. (Hons.)"), (9, "B.Sc."), (10, "B.Sc. (Hons.)"), (11, "B. Ed."), (12, "LLB"), (13, "BE"), (14, "B. Tech"), (15, "AMIE (Part A & Part B)"), (16, "B.Sc. (Engg.)"), (17, "BCA"), (18, "BBA"), (19, "Graduation issued by Defence (Indian Army, Air Force, Navy)"), (20, "B. Lib."), (21, "B. Pharm."), (22, "ICWA"), (23, "CA"), (24, "PG Diploma"), (25, "MA"), (26, "M.Com."), (27, "M. Sc."), (28, "M.Ed."), (29, "LLM"), (30, "ME"), (31, "M. Tech."), (32, "M. Sc. (Engg.)"), (33, "MCA"), (34, "MBA"), (35, "Others"))

AGE_RELAXATION_CODE = ((1, "SC/ ST candidates"), (2, "OBC candidates"), (3, "PwD (Unreserved) candidates"), (4, "PwD (OBC) candidates"), (5, "PwD (SC/ ST) candidates"), (6, "Ex-Servicemen (ESM)"))

CENTER1 = ((1, "Mumbai"), (2, "Delhi"), (3, "Bangalore"), (4, "Hyderabad"), (5, "Ahmedabad"), (6, "Chennai"), (7, "Kolkata"), (8, "Surat"), (9, "Pune"), (10, "Jaipur"), (11, "Bhagalpuri"), (12, "Darbhanga"), (13, "Muzaffarpur"), (14, "Patna"), (15, "Purnea"), (16, "Gorakhpur"), (17, "Jhansi"), (18, "Kanpur"), (19, "Lucknow"), (20, "Meerut"), (21, "Prayagraj"), (22, "Varanasi"), (23, "Port Blair"), (24, "Ranchi"), (25, "Balasore"), (26, "Berhampore"), (27, "Bhubaneshwar"), (28, "Cuttack"), (29, "Dhenkenal"), (30, "Rourkela"), (31, "Sambalpur"), (32, "Gangtok"), (33, "Hoogly"), (34, "Kolkata"), (35, "Siliguri"), (36, "Kavaratti"), (37, "Belagavi"), (38, "Bengaluru"), (39, "Hubballi"), (40, "Kalaburagi"), (41, "Mangaluru"), (42, "Mysuru"), (43, "Shivamogga"), (44, "Udupi"), (45, "Ernakulam"), (46, "Kannur"), (47, "Kollam"), (48, "Kottayam"), (49, "Kozhikode"), (50, "Thrissur"), (51, "Thiruvananthapuram"), (52, "Bilaspur"), (53, "Raipur"), (54, "Durg-Bhilai"), (55, "Bhopal"), (56, "Gwalior"), (57, "Indore"), (58, "Jabalpur"), (59, "Satna"), (60, "Ujjain"), (61, "Itanagar"), (62, "Dibrugarh"), (63, "Guwahati"), (64, "Jorhat"), (65, "Silchar"), (66, "Imphal"), (67, "Churachandpuri"), (68, "Ukhrul"), (69, "Shillong"), (70, "Aizwal"), (71, "Kohima"), (72, "Agartala"), (73, "Ajmer"), (74, "Alwar"), (75, "Bharatpur"), (76, "Bikaner"), (77, "Jodhpur"), (78, "Kota"), (79, "Sriganganagar"), (80, "Udaipur"), (81, "Sikar"), (82, "Dehradun"), (83, "Haldwani"), (84, "Haridwar"), (85, "Roorkee"), (86, "Chandigarh"), (87, "Hamirpur"), (88, "Shimla"), (89, "Jammu"), (90, "Samba"), (91, "Srinagar"), (92, "Leh"), (93, "Amritsar"), (94, "Jalandhar"), (95, "Ludhiana"), (96, "Chirala"), (97, "Guntur"), (98, "Kakinada"), (99, "Kurnool"), (100, "Nellore"), (101, "Rajahmundry"), (102, "Tirupati"), (103, "Vizianagaram"), (104, "Vijaywada"), (105, "Vishakhapatnam"), (106, "Puducherry"), (107, "Coimbatore"), (108, "Madurai"), (109, "Salem"), (110, "Tiruchirapalli"), (111, "Tirunelveli"), (112, "Vellore"), (113, "Karimnagar"), (114, "Warangal"), (115, "Panaji"), (116, "Anand"), (117, "Gandhinagar"), (118, "Mehsana"), (119, "Rajkot"), (120, "Vadodara"), (121, "Amravati"), (123, "Aurangabad"), (124, "Jalgaon"), (125, "Kolhapur"), (126, "Nagpur"), (127, "Nanded"), (128, "Nashik"))

CENTER2 = ((1, "Mumbai"), (2, "Delhi"), (3, "Bangalore"), (4, "Hyderabad"), (5, "Ahmedabad"), (6, "Chennai"), (7, "Kolkata"), (8, "Surat"), (9, "Pune"), (10, "Jaipur"), (11, "Bhagalpuri"), (12, "Darbhanga"), (13, "Muzaffarpur"), (14, "Patna"), (15, "Purnea"), (16, "Gorakhpur"), (17, "Jhansi"), (18, "Kanpur"), (19, "Lucknow"), (20, "Meerut"), (21, "Prayagraj"), (22, "Varanasi"), (23, "Port Blair"), (24, "Ranchi"), (25, "Balasore"), (26, "Berhampore"), (27, "Bhubaneshwar"), (28, "Cuttack"), (29, "Dhenkenal"), (30, "Rourkela"), (31, "Sambalpur"), (32, "Gangtok"), (33, "Hoogly"), (34, "Kolkata"), (35, "Siliguri"), (36, "Kavaratti"), (37, "Belagavi"), (38, "Bengaluru"), (39, "Hubballi"), (40, "Kalaburagi"), (41, "Mangaluru"), (42, "Mysuru"), (43, "Shivamogga"), (44, "Udupi"), (45, "Ernakulam"), (46, "Kannur"), (47, "Kollam"), (48, "Kottayam"), (49, "Kozhikode"), (50, "Thrissur"), (51, "Thiruvananthapuram"), (52, "Bilaspur"), (53, "Raipur"), (54, "Durg-Bhilai"), (55, "Bhopal"), (56, "Gwalior"), (57, "Indore"), (58, "Jabalpur"), (59, "Satna"), (60, "Ujjain"), (61, "Itanagar"), (62, "Dibrugarh"), (63, "Guwahati"), (64, "Jorhat"), (65, "Silchar"), (66, "Imphal"), (67, "Churachandpuri"), (68, "Ukhrul"), (69, "Shillong"), (70, "Aizwal"), (71, "Kohima"), (72, "Agartala"), (73, "Ajmer"), (74, "Alwar"), (75, "Bharatpur"), (76, "Bikaner"), (77, "Jodhpur"), (78, "Kota"), (79, "Sriganganagar"), (80, "Udaipur"), (81, "Sikar"), (82, "Dehradun"), (83, "Haldwani"), (84, "Haridwar"), (85, "Roorkee"), (86, "Chandigarh"), (87, "Hamirpur"), (88, "Shimla"), (89, "Jammu"), (90, "Samba"), (91, "Srinagar"), (92, "Leh"), (93, "Amritsar"), (94, "Jalandhar"), (95, "Ludhiana"), (96, "Chirala"), (97, "Guntur"), (98, "Kakinada"), (99, "Kurnool"), (100, "Nellore"), (101, "Rajahmundry"), (102, "Tirupati"), (103, "Vizianagaram"), (104, "Vijaywada"), (105, "Vishakhapatnam"), (106, "Puducherry"), (107, "Coimbatore"), (108, "Madurai"), (109, "Salem"), (110, "Tiruchirapalli"), (111, "Tirunelveli"), (112, "Vellore"), (113, "Karimnagar"), (114, "Warangal"), (115, "Panaji"), (116, "Anand"), (117, "Gandhinagar"), (118, "Mehsana"), (119, "Rajkot"), (120, "Vadodara"), (121, "Amravati"), (123, "Aurangabad"), (124, "Jalgaon"), (125, "Kolhapur"), (126, "Nagpur"), (127, "Nanded"), (128, "Nashik"))

CENTER3 = ((1, "Mumbai"), (2, "Delhi"), (3, "Bangalore"), (4, "Hyderabad"), (5, "Ahmedabad"), (6, "Chennai"), (7, "Kolkata"), (8, "Surat"), (9, "Pune"), (10, "Jaipur"), (11, "Bhagalpuri"), (12, "Darbhanga"), (13, "Muzaffarpur"), (14, "Patna"), (15, "Purnea"), (16, "Gorakhpur"), (17, "Jhansi"), (18, "Kanpur"), (19, "Lucknow"), (20, "Meerut"), (21, "Prayagraj"), (22, "Varanasi"), (23, "Port Blair"), (24, "Ranchi"), (25, "Balasore"), (26, "Berhampore"), (27, "Bhubaneshwar"), (28, "Cuttack"), (29, "Dhenkenal"), (30, "Rourkela"), (31, "Sambalpur"), (32, "Gangtok"), (33, "Hoogly"), (34, "Kolkata"), (35, "Siliguri"), (36, "Kavaratti"), (37, "Belagavi"), (38, "Bengaluru"), (39, "Hubballi"), (40, "Kalaburagi"), (41, "Mangaluru"), (42, "Mysuru"), (43, "Shivamogga"), (44, "Udupi"), (45, "Ernakulam"), (46, "Kannur"), (47, "Kollam"), (48, "Kottayam"), (49, "Kozhikode"), (50, "Thrissur"), (51, "Thiruvananthapuram"), (52, "Bilaspur"), (53, "Raipur"), (54, "Durg-Bhilai"), (55, "Bhopal"), (56, "Gwalior"), (57, "Indore"), (58, "Jabalpur"), (59, "Satna"), (60, "Ujjain"), (61, "Itanagar"), (62, "Dibrugarh"), (63, "Guwahati"), (64, "Jorhat"), (65, "Silchar"), (66, "Imphal"), (67, "Churachandpuri"), (68, "Ukhrul"), (69, "Shillong"), (70, "Aizwal"), (71, "Kohima"), (72, "Agartala"), (73, "Ajmer"), (74, "Alwar"), (75, "Bharatpur"), (76, "Bikaner"), (77, "Jodhpur"), (78, "Kota"), (79, "Sriganganagar"), (80, "Udaipur"), (81, "Sikar"), (82, "Dehradun"), (83, "Haldwani"), (84, "Haridwar"), (85, "Roorkee"), (86, "Chandigarh"), (87, "Hamirpur"), (88, "Shimla"), (89, "Jammu"), (90, "Samba"), (91, "Srinagar"), (92, "Leh"), (93, "Amritsar"), (94, "Jalandhar"), (95, "Ludhiana"), (96, "Chirala"), (97, "Guntur"), (98, "Kakinada"), (99, "Kurnool"), (100, "Nellore"), (101, "Rajahmundry"), (102, "Tirupati"), (103, "Vizianagaram"), (104, "Vijaywada"), (105, "Vishakhapatnam"), (106, "Puducherry"), (107, "Coimbatore"), (108, "Madurai"), (109, "Salem"), (110, "Tiruchirapalli"), (111, "Tirunelveli"), (112, "Vellore"), (113, "Karimnagar"), (114, "Warangal"), (115, "Panaji"), (116, "Anand"), (117, "Gandhinagar"), (118, "Mehsana"), (119, "Rajkot"), (120, "Vadodara"), (121, "Amravati"), (123, "Aurangabad"), (124, "Jalgaon"), (125, "Kolhapur"), (126, "Nagpur"), (127, "Nanded"), (128, "Nashik"))

TYPE_OF_DISABILITES = ((0, "------"), (1, "Vision Impairment"), (2, "Deaf or hard of hearing"), (3, "Mental health conditions"), (4, "Intellectual disability"), (5, "Acquired brain injury"), (6, "Autism spectrum disorder"), (7, "Physical disability"))

CHANGED_NAME = ((0, "Yes"), (1, "No"))

TYPE_OF_ID = ((1, "Driving License"), (2, "Employer ID"), (3, "PAN Card"), (4, "Passport"), (5, "School/College ID Card"), (6, "Voter ID Card"))

EDUCATION_BOARD = ((1, "Central Board of Secondary Education (CBSE)"), (2, "Council for The Indian School Certificate Examinations (ICSE)"), (3, "National Institute of Open Schooling (NIOS)"), (4, "Aligarh Muslim University, Aligarh"), (5, "Andhra Pradesh Open School Society"), (6, "Assam Sanskrit Board"), (7, "Banasthali Vidyapith, Rajasthan"), (8, "Bihar Board of Open Schooling And Examination"), (9, "Bihar Sanskrit Shiksha Board"), (10, "Bihar School Examination Board"), (11, "Bihar State Madrasa Education Board"), (12, "Board of High School And Intermediate Education Uttar Pradesh"), (13, "Board of School Education Haryana"), (14, "Board of Secondary Education Andhra Pradesh"), (15, "Board of Secondary Education Assam"), (16, "Board of Secondary Education, Odisha"), (17, "Board of Secondary Education, Rajasthan"), (18, "Chhatisgarh State Open School"), (19, "Chhattisgarh Board of Secondary Education"), (20, "Chhattisgarh Sanskrit Board"), (21, "Directorate of Army Education, New Delhi"), (22, "Directorate of Government Examinations, Tamil Nadu"), (23, "Goa Board of Secondary And Higher Secondary Education"), (24, "Gujarat Secondary And Higher Secondary Education Board"), (25, "Gurukul Kangri Vishwavidyalaya, Haridwar"), (26, "Haryana Open School"), (27, "Himachal Pradesh Board of School Education"), (28, "Himachal Pradesh State Open School"), (29, "Jamia Miliya Hamdard University"), (30, "Jamia Miliya Islamia, New Delhi"), (31, "Jammu and Kashmir State Board of School Education"), (32, "Jammu and Kashmir State Open School"), (33, "Jharkhand Academic Council Ranchi"), (34, "Karnataka Secondary Education Examination Board"), (35, "Kerala Board of Public Examinations"), (36, "Madhya Pradesh Board of Secondary Education"), (37, "Madhya Pradesh State Open School"), (38, "Maharashtra State Board of Secondary And Higher Secondary Education"), (39, "Manipur Board of Secondary Education"), (40, "Meghalaya Board of School Education"), (41, "Mizoram Board of School Education"), (42, "Nagaland Board of School Education"), (43, "Punjab School Education Board"), (44, "Rajasthan State Open School"), (45, "Rashtriya Sanskrit Sansthan, New Delhi"), (46, "State Council for Open and Lifelong Education - Kerala"), (47, "State Madrassa Education Board Assam"), (48, "Tamil Nadu Board of Secondary Education"), (49, "Tamilnadu Council for Open And Distance Learning"), (50, "Tripura Board of Secondary Education"), (51, "Uttarakhand Board of School Education"), (52, "Uttrakhand Vidyalayi Shiksha Parishad"), (53, "Uttranchal Shiksha Avam Pariksha Parishad"), (54, "West Bengal Board of Madrasa Education"), (55, "West Bengal Board of Secondary Education"), (56, "The West Bengal Council of Rabindra Open Schooling"), (57, "International Board"), (58, "Board of Secondary Education Telangana"), (59, "UP Board of Madrasa Education"), (60, "Maharshi Patanjali Sanskrit Sansthan Bhopal"), (61, "Visva Bharti University"), (62, "Dayalbagh Education Institute"), (63, "Gurukul Mahavidyalaya Jwalapur Haridwar"), (64, "Uttar Pradesh Board of Secondary Sanskrit Education"), (65, "Jharkhand Secondary Examination Board"), (66, "Sampoornanand Sanskrit Vishwavidyalaya"), (67, "Telangana Open School Society"))

YEAR_OF_PASSING = ((1, "2021"), (2, "2020"), (3, "2019"), (4, "2018"), (5, "2017"), (6, "2016"), (7, "2015"), (8, "2014"), (9, "2013"), (10, "2012"), (11, "2011"), (12, "2010"), (13, "2009"), (14, "2008"), (15, "2007"), (16, "2006"), (17, "2005"), (18, "2004"), (19, "2003"), (20, "2002"), (21, "2001"), (22, "2000"), (23, "1999"), (23, "1998"), (24, "1997"), (25, "1996"), (26, "1995"), (27, "1994"), (28, "1993"), (29, "1992"), (30, "1991"), (31, "1990"), (32, "1989"), (33, "1988"), (34, "1987"), (35, "1986"), (36, "1985"), (37, "1984"), (38, "1983"), (39, "1982"), (40, "1981"), (41, "1980"), (42, "1979"), (43, "1978"), (44, "1977"), (45, "1976"), (46, "1975"), (47, "1974"), (48, "1973"), (49, "1972"), (50, "1971"), (51, "1970"), (52, "1969"), (53, "1968"), (54, "1967"), (55, "1966"), (56, "1965"), (57, "1964"), (58, "1963"), (59, "1962"), (60, "1961"))

GENDER = ((0, "Male"), (1, "Female"), (2, "Transgender"))

EDUCATION_LEVEL = ((1, "Matriculation (10th)"), (2, "Higher Secondary (10+2"), (3, "Diploma"), (4, "Graduation"), (5, "Post Graduation"), (6, "Ph.D"))

STATE = ((1, "Andaman and Nicobar Islands"), (2, "Andhra Pradesh"), (3, "Arunachal Pradesh"), (4, "Assam"), (5, "Bihar"), (6, "Chandigarh"), (7, "Chhattisgarh"), (8, "Dadra and Nagar Haveli and Daman and Diu"), (9, "Delhi"), (10, "Goa"), (11, "Gujarat"), (12, "Haryana"), (13, "Himachal Pradesh"), (14, "Jammu and Kashmir"), (15, "Jharkhand"), (16, "Karnataka"), (17, "Kerala"), (18, "Ladakh"), (19, "Lakshadweep"), (20, "Madhya Pradesh"), (21, "Maharashtra"), (22, "Manipur"), (23, "Meghalaya"), (24, "Mizoram"), (25, "Nagaland"), (26, "Odisha"), (27, "Puducherry"), (28, "Punjab"), (29, "Rajasthan"), (30, "Sikkim"), (31, "Tamil Nadu"), (32, "Telangana"), (33, "Tripura"), (34, "Uttarakhand"), (35, "Uttar Pradesh"), (36, "West Bengal"))


DISTRICT = {
        '1':[
            "Nicobar",
            "North and Middle Andaman",
            "South Andaman"
        ],
        '2':[  
            "Anantapur",
            "Chittoor",
            "East Godavari",
            "Guntur",
            "Krishna",
            "Kurnool",
            "Nellore",
            "Prakasam",
            "Srikakulam",
            "Visakhapatnam",
            "Vizianagaram",
            "West Godavari",
            "YSR Kadapa"
         ],
         '3':[  
            "Tawang",
            "West Kameng",
            "East Kameng",
            "Papum Pare",
            "Kurung Kumey",
            "Kra Daadi",
            "Lower Subansiri",
            "Upper Subansiri",
            "West Siang",
            "East Siang",
            "Siang",
            "Upper Siang",
            "Lower Siang",
            "Lower Dibang Valley",
            "Dibang Valley",
            "Anjaw",
            "Lohit",
            "Namsai",
            "Changlang",
            "Tirap",
            "Longding"
         ],
         '4':[  
            "Baksa",
            "Barpeta",
            "Biswanath",
            "Bongaigaon",
            "Cachar",
            "Charaideo",
            "Chirang",
            "Darrang",
            "Dhemaji",
            "Dhubri",
            "Dibrugarh",
            "Goalpara",
            "Golaghat",
            "Hailakandi",
            "Hojai",
            "Jorhat",
            "Kamrup Metropolitan",
            "Kamrup",
            "Karbi Anglong",
            "Karimganj",
            "Kokrajhar",
            "Lakhimpur",
            "Majuli",
            "Morigaon",
            "Nagaon",
            "Nalbari",
            "Dima Hasao",
            "Sivasagar",
            "Sonitpur",
            "South Salmara-Mankachar",
            "Tinsukia",
            "Udalguri",
            "West Karbi Anglong"
         ],
         '5':[  
            "Araria",
            "Arwal",
            "Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "Darbhanga",
            "East Champaran (Motihari)",
            "Gaya",
            "Gopalganj",
            "Jamui",
            "Jehanabad",
            "Kaimur (Bhabua)",
            "Katihar",
            "Khagaria",
            "Kishanganj",
            "Lakhisarai",
            "Madhepura",
            "Madhubani",
            "Munger (Monghyr)",
            "Muzaffarpur",
            "Nalanda",
            "Nawada",
            "Patna",
            "Purnia (Purnea)",
            "Rohtas",
            "Saharsa",
            "Samastipur",
            "Saran",
            "Sheikhpura",
            "Sheohar",
            "Sitamarhi",
            "Siwan",
            "Supaul",
            "Vaishali",
            "West Champaran"
         ],
         '6':[  
            "Chandigarh"
         ],
         '7':[  
            "Balod",
            "Baloda Bazar",
            "Balrampur",
            "Bastar",
            "Bemetara",
            "Bijapur",
            "Bilaspur",
            "Dantewada (South Bastar)",
            "Dhamtari",
            "Durg",
            "Gariyaband",
            "Janjgir-Champa",
            "Jashpur",
            "Kabirdham (Kawardha)",
            "Kanker (North Bastar)",
            "Kondagaon",
            "Korba",
            "Korea (Koriya)",
            "Mahasamund",
            "Mungeli",
            "Narayanpur",
            "Raigarh",
            "Raipur",
            "Rajnandgaon",
            "Sukma",
            "Surajpur  ",
            "Surguja"
         ],
         '8':[  
            "Dadra & Nagar Haveli",
            "Daman",
            "Diu"
         ],
         '9':[  
            "Central Delhi",
            "East Delhi",
            "New Delhi",
            "North Delhi",
            "North East  Delhi",
            "North West  Delhi",
            "Shahdara",
            "South Delhi",
            "South East Delhi",
            "South West  Delhi",
            "West Delhi"
         ],
         '10':[  
            "North Goa",
            "South Goa"
         ],
         '11':[  
            "Ahmedabad",
            "Amreli",
            "Anand",
            "Aravalli",
            "Banaskantha (Palanpur)",
            "Bharuch",
            "Bhavnagar",
            "Botad",
            "Chhota Udepur",
            "Dahod",
            "Dangs (Ahwa)",
            "Devbhoomi Dwarka",
            "Gandhinagar",
            "Gir Somnath",
            "Jamnagar",
            "Junagadh",
            "Kachchh",
            "Kheda (Nadiad)",
            "Mahisagar",
            "Mehsana",
            "Morbi",
            "Narmada (Rajpipla)",
            "Navsari",
            "Panchmahal (Godhra)",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Sabarkantha (Himmatnagar)",
            "Surat",
            "Surendranagar",
            "Tapi (Vyara)",
            "Vadodara",
            "Valsad"
         ],
         '12':[  
            "Ambala",
            "Bhiwani",
            "Charkhi Dadri",
            "Faridabad",
            "Fatehabad",
            "Gurgaon",
            "Hisar",
            "Jhajjar",
            "Jind",
            "Kaithal",
            "Karnal",
            "Kurukshetra",
            "Mahendragarh",
            "Mewat",
            "Palwal",
            "Panchkula",
            "Panipat",
            "Rewari",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Yamunanagar"
         ],
         '13':[  
            "Bilaspur",
            "Chamba",
            "Hamirpur",
            "Kangra",
            "Kinnaur",
            "Kullu",
            "Lahaul &amp; Spiti",
            "Mandi",
            "Shimla",
            "Sirmaur (Sirmour)",
            "Solan",
            "Una"
         ],
         '14':[  
            "Anantnag",
            "Bandipore",
            "Baramulla",
            "Budgam",
            "Doda",
            "Ganderbal",
            "Jammu",
            "Kargil",
            "Kathua",
            "Kishtwar",
            "Kulgam",
            "Kupwara",
            "Leh",
            "Poonch",
            "Pulwama",
            "Rajouri",
            "Ramban",
            "Reasi",
            "Samba",
            "Shopian",
            "Srinagar",
            "Udhampur"
         ],
         '15':[  
            "Bokaro",
            "Chatra",
            "Deoghar",
            "Dhanbad",
            "Dumka",
            "East Singhbhum",
            "Garhwa",
            "Giridih",
            "Godda",
            "Gumla",
            "Hazaribag",
            "Jamtara",
            "Khunti",
            "Koderma",
            "Latehar",
            "Lohardaga",
            "Pakur",
            "Palamu",
            "Ramgarh",
            "Ranchi",
            "Sahibganj",
            "Seraikela-Kharsawan",
            "Simdega",
            "West Singhbhum"
         ],
         '16':[  
            "Bagalkot",
            "Ballari (Bellary)",
            "Belagavi (Belgaum)",
            "Bengaluru (Bangalore) Rural",
            "Bengaluru (Bangalore) Urban",
            "Bidar",
            "Chamarajanagar",
            "Chikballapur",
            "Chikkamagaluru (Chikmagalur)",
            "Chitradurga",
            "Dakshina Kannada",
            "Davangere",
            "Dharwad",
            "Gadag",
            "Hassan",
            "Haveri",
            "Kalaburagi (Gulbarga)",
            "Kodagu",
            "Kolar",
            "Koppal",
            "Mandya",
            "Mysuru (Mysore)",
            "Raichur",
            "Ramanagara",
            "Shivamogga (Shimoga)",
            "Tumakuru (Tumkur)",
            "Udupi",
            "Uttara Kannada (Karwar)",
            "Vijayapura (Bijapur)",
            "Yadgir"
         ],
         '17':[  
            "Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kannur",
            "Kasaragod",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thiruvananthapuram",
            "Thrissur",
            "Wayanad"
         ],
         '18':[  
            "Kargil",
            "Leh"
         ],
         '19':[  
            "Agatti",
            "Amini",
            "Androth",
            "Bithra",
            "Chethlath",
            "Kavaratti",
            "Kadmath",
            "Kalpeni",
            "Kilthan",
            "Minicoy"
         ],
         '20':[  
            "Agar Malwa",
            "Alirajpur",
            "Anuppur",
            "Ashoknagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dindori",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa",
            "Khargone",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panna",
            "Raisen",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Satna",
            "Sehore",
            "Seoni",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha"
         ],
         '21':[  
            "Ahmednagar",
            "Akola",
            "Amravati",
            "Aurangabad",
            "Beed",
            "Bhandara",
            "Buldhana",
            "Chandrapur",
            "Dhule",
            "Gadchiroli",
            "Gondia",
            "Hingoli",
            "Jalgaon",
            "Jalna",
            "Kolhapur",
            "Latur",
            "Mumbai City",
            "Mumbai Suburban",
            "Nagpur",
            "Nanded",
            "Nandurbar",
            "Nashik",
            "Osmanabad",
            "Palghar",
            "Parbhani",
            "Pune",
            "Raigad",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sindhudurg",
            "Solapur",
            "Thane",
            "Wardha",
            "Washim",
            "Yavatmal"
         ],
         '22':[  
            "Bishnupur",
            "Chandel",
            "Churachandpur",
            "Imphal East",
            "Imphal West",
            "Jiribam",
            "Kakching",
            "Kamjong",
            "Kangpokpi",
            "Noney",
            "Pherzawl",
            "Senapati",
            "Tamenglong",
            "Tengnoupal",
            "Thoubal",
            "Ukhrul"
         ],
         '23':[  
            "East Garo Hills",
            "East Jaintia Hills",
            "East Khasi Hills",
            "North Garo Hills",
            "Ri Bhoi",
            "South Garo Hills",
            "South West Garo Hills ",
            "South West Khasi Hills",
            "West Garo Hills",
            "West Jaintia Hills",
            "West Khasi Hills"
         ],
         '24':[  
            "Aizawl",
            "Champhai",
            "Kolasib",
            "Lawngtlai",
            "Lunglei",
            "Mamit",
            "Saiha",
            "Serchhip"
         ],
         '25':[  
            "Dimapur",
            "Kiphire",
            "Kohima",
            "Longleng",
            "Mokokchung",
            "Mon",
            "Peren",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto"
         ],
         '26':[  
            "Angul",
            "Balangir",
            "Balasore",
            "Bargarh",
            "Bhadrak",
            "Boudh",
            "Cuttack",
            "Deogarh",
            "Dhenkanal",
            "Gajapati",
            "Ganjam",
            "Jagatsinghapur",
            "Jajpur",
            "Jharsuguda",
            "Kalahandi",
            "Kandhamal",
            "Kendrapara",
            "Kendujhar (Keonjhar)",
            "Khordha",
            "Koraput",
            "Malkangiri",
            "Mayurbhanj",
            "Nabarangpur",
            "Nayagarh",
            "Nuapada",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Sonepur",
            "Sundargarh"
         ],
         '27':[  
            "Karaikal",
            "Mahe",
            "Pondicherry",
            "Yanam"
         ],
         '28':[  
            "Amritsar",
            "Barnala",
            "Bathinda",
            "Faridkot",
            "Fatehgarh Sahib",
            "Fazilka",
            "Ferozepur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Muktsar",
            "Nawanshahr (Shahid Bhagat Singh Nagar)",
            "Pathankot",
            "Patiala",
            "Rupnagar",
            "Sahibzada Ajit Singh Nagar (Mohali)",
            "Sangrur",
            "Tarn Taran"
         ],
         '29':[  
            "Ajmer",
            "Alwar",
            "Banswara",
            "Baran",
            "Barmer",
            "Bharatpur",
            "Bhilwara",
            "Bikaner",
            "Bundi",
            "Chittorgarh",
            "Churu",
            "Dausa",
            "Dholpur",
            "Dungarpur",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jalore",
            "Jhalawar",
            "Jhunjhunu",
            "Jodhpur",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Pratapgarh",
            "Rajsamand",
            "Sawai Madhopur",
            "Sikar",
            "Sirohi",
            "Sri Ganganagar",
            "Tonk",
            "Udaipur"
         ],
         '30':[  
            "East Sikkim",
            "North Sikkim",
            "South Sikkim",
            "West Sikkim"
         ],
         '31':[  
            "Ariyalur",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kanchipuram",
            "Kanyakumari",
            "Karur",
            "Krishnagiri",
            "Madurai",
            "Nagapattinam",
            "Namakkal",
            "Nilgiris",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Salem",
            "Sivaganga",
            "Thanjavur",
            "Theni",
            "Thoothukudi (Tuticorin)",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tiruppur",
            "Tiruvallur",
            "Tiruvannamalai",
            "Tiruvarur",
            "Vellore",
            "Viluppuram",
            "Virudhunagar"
         ],
         '32':[  
            "Adilabad",
            "Bhadradri Kothagudem",
            "Hyderabad",
            "Jagtial",
            "Jangaon",
            "Jayashankar Bhoopalpally",
            "Jogulamba Gadwal",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Komaram Bheem Asifabad",
            "Mahabubabad",
            "Mahabubnagar",
            "Mancherial",
            "Medak",
            "Medchal",
            "Nagarkurnool",
            "Nalgonda",
            "Nirmal",
            "Nizamabad",
            "Peddapalli",
            "Rajanna Sircilla",
            "Rangareddy",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Wanaparthy",
            "Warangal (Rural)",
            "Warangal (Urban)",
            "Yadadri Bhuvanagiri"
         ],
         '33':[  
            "Dhalai",
            "Gomati",
            "Khowai",
            "North Tripura",
            "Sepahijala",
            "South Tripura",
            "Unakoti",
            "West Tripura"
         ],
         '34':[  
            "Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi"
         ],
         '35':[  
            "Agra",
            "Aligarh",
            "Allahabad",
            "Ambedkar Nagar",
            "Amethi (Chatrapati Sahuji Mahraj Nagar)",
            "Amroha (J.P. Nagar)",
            "Auraiya",
            "Azamgarh",
            "Baghpat",
            "Bahraich",
            "Ballia",
            "Balrampur",
            "Banda",
            "Barabanki",
            "Bareilly",
            "Basti",
            "Bhadohi",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Chandauli",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Etawah",
            "Faizabad",
            "Farrukhabad",
            "Fatehpur",
            "Firozabad",
            "Gautam Buddha Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Gorakhpur",
            "Hamirpur",
            "Hapur (Panchsheel Nagar)",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Kannauj",
            "Kanpur Dehat",
            "Kanpur Nagar",
            "Kanshiram Nagar (Kasganj)",
            "Kaushambi",
            "Kushinagar (Padrauna)",
            "Lakhimpur - Kheri",
            "Lalitpur",
            "Lucknow",
            "Maharajganj",
            "Mahoba",
            "Mainpuri",
            "Mathura",
            "Mau",
            "Meerut",
            "Mirzapur",
            "Moradabad",
            "Muzaffarnagar",
            "Pilibhit",
            "Pratapgarh",
            "RaeBareli",
            "Rampur",
            "Saharanpur",
            "Sambhal (Bhim Nagar)",
            "Sant Kabir Nagar",
            "Shahjahanpur",
            "Shamali (Prabuddh Nagar)",
            "Shravasti",
            "Siddharth Nagar",
            "Sitapur",
            "Sonbhadra",
            "Sultanpur",
            "Unnao",
            "Varanasi"
         ],
         '36':[  
            "Alipurduar",
            "Bankura",
            "Birbhum",
            "Burdwan (Bardhaman)",
            "Cooch Behar",
            "Dakshin Dinajpur (South Dinajpur)",
            "Darjeeling",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Kalimpong",
            "Kolkata",
            "Malda",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "Paschim Medinipur (West Medinipur)",
            "Purba Medinipur (East Medinipur)",
            "Purulia",
            "South 24 Parganas",
            "Uttar Dinajpur (North Dinajpur)"
         ]
         }

COUNTRY = (
    (1, 'AFGHANISTAN'),
    (2, 'ALBANIA'),
    (3, 'ALGERIA'),
    (4, 'AMERICAN SAMOA'),
    (5, 'ANDORRA'),
    (6, 'ANGOLA'),
    (7, 'ANGUILLA'),
    (8, 'ANTARCTICA'),
    (9, 'ANTIGUA AND BARBUDA'),
    (10, 'ARGENTINA'),
    (11, 'ARMENIA'),
    (12, 'ARUBA'),
    (13, 'AUSTRALIA'),
    (14, 'AUSTRIA'),
    (15, 'AZERBAIJAN'),
    (16, 'BAHAMAS'),
    (17, 'BAHRAIN'),
    (18, 'BANGLADESH'),
    (19, 'BARBADOS'),
    (20, 'BELARUS'),
    (21, 'BELGIUM'),
    (22, 'BELIZE'),
    (23, 'BENIN'),
    (24, 'BERMUDA'),
    (25, 'BHUTAN'),
    (26, 'BOLIVIA'),
    (27, 'BOSNIA AND HERZEGOVINA'),
    (28, 'BOTSWANA'),
    (29, 'BOUVET ISLAND'),
    (30, 'BRAZIL'),
    (31, 'BRITISH INDIAN OCEAN TERRITORY'),
    (32, 'BRUNEI DARUSSALAM'),
    (33, 'BULGARIA'),
    (34, 'BURKINA FASO'),
    (35, 'BURUNDI'),
    (36, 'CAMBODIA'),
    (37, 'CAMEROON'),
    (38, 'CANADA'),
    (39, 'CAPE VERDE'),
    (40, 'CAYMAN ISLANDS'),
    (41, 'CENTRAL AFRICAN REPUBLIC'),
    (42, 'CHAD'),
    (43, 'CHILE'),
    (44, 'CHINA'),
    (45, 'CHRISTMAS ISLAND'),
    (46, 'COCOS (KEELING) ISLANDS'),
    (47, 'COLOMBIA'),
    (48, 'COMOROS'),
    (49, 'CONGO'),
    (50, 'CONGO, THE DEMOCRATIC REPUBLIC OF'),
    (51, 'COOK ISLANDS'),
    (52, 'COSTA RICA'),
    (53, "CÃ”TE D'IVOIRE"),
    (54, 'CROATIA'),
    (55, 'CUBA'),
    (56, 'CYPRUS'),
    (57, 'CZECH REPUBLIC'),
    (58, 'DENMARK'),
    (59, 'DJIBOUTI'),
    (60, 'DOMINICA'),
    (61, 'DOMINICAN REPUBLIC'),
    (62, 'ECUADOR'),
    (63, 'EGYPT'),
    (64, 'EL SALVADOR'),
    (65, 'EQUATORIAL GUINEA'),
    (66, 'ERITREA'),
    (67, 'ESTONIA'),
    (68, 'ETHIOPIA'),
    (69, 'FALKLAND ISLANDS (MALVINAS)'),
    (70, 'FAROE ISLANDS'),
    (71, 'FIJI'),
    (72, 'FINLAND'),
    (73, 'FRANCE'),
    (74, 'FRENCH GUIANA'),
    (75, 'FRENCH POLYNESIA'),
    (76, 'FRENCH SOUTHERN TERRITORIES'),
    (77, 'GABON'),
    (78, 'GAMBIA'),
    (79, 'GEORGIA'),
    (80, 'GERMANY'),
    (81, 'GHANA'),
    (82, 'GIBRALTAR'),
    (83, 'GREECE'),
    (84, 'GREENLAND'),
    (85, 'GRENADA'),
    (86, 'GUADELOUPE'),
    (87, 'GUAM'),
    (88, 'GUATEMALA'),
    (89, 'GUINEA'),
    (90, 'GUINEA'),
    (91, 'GUYANA'),
    (92, 'HAITI'),
    (93, 'HEARD ISLAND AND MCDONALD ISLANDS'),
    (94, 'HONDURAS'),
    (95, 'HONG KONG'),
    (96, 'HUNGARY'),
    (97, 'ICELAND'),
    (98, 'INDIA'),
    (99, 'INDONESIA'),
    (100, 'IRAN, ISLAMIC REPUBLIC OF'),
    (101, 'IRAQ'),
    (102, 'IRELAND'),
    (103, 'ISRAEL'),
    (104, 'ITALY'),
    (105, 'JAMAICA'),
    (106, 'JAPAN'),
    (107, 'JORDAN'),
    (108, 'KAZAKHSTAN'),
    (109, 'KENYA'),
    (110, 'KIRIBATI'),
    (111, "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
    (112, 'KOREA, REPUBLIC OF'),
    (113, 'KUWAIT'),
    (114, 'KYRGYZSTAN'),
    (115, "LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
    (116, 'LATVIA'),
    (117, 'LEBANON'),
    (118, 'LESOTHO'),
    (119, 'LIBERIA'),
    (120, 'LIBYAN ARAB JAMAHIRIYA'),
    (121, 'LIECHTENSTEIN'),
    (122, 'LITHUANIA'),
    (123, 'LUXEMBOURG'),
    (124, 'MACAO'),
    (125, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'),
    (126, 'MADAGASCAR'),
    (127, 'MALAWI'),
    (128, 'MALAYSIA'),
    (129, 'MALDIVES'),
    (130, 'MALI'),
    (131, 'MALTA'),
    (132, 'MARSHALL ISLANDS'),
    (133, 'MARTINIQUE'),
    (134, 'MAURITANIA'),
    (135, 'MAURITIUS'),
    (136, 'MAYOTTE'),
    (137, 'MEXICO'),
    (138, 'MICRONESIA, FEDERATED STATES OF'),
    (139, 'MOLDOVA, REPUBLIC OF'),
    (140, 'MONACO'),
    (141, 'MONGOLIA'),
    (142, 'MONTSERRAT'),
    (143, 'MOROCCO'),
    (144, 'MOZAMBIQUE'),
    (145, 'MYANMAR'),
    (146, 'NAMIBIA'),
    (147, 'NAURU'),
    (148, 'NEPAL'),
    (149, 'NETHERLANDS'),
    (150, 'NETHERLANDS ANTILLES'),
    (151, 'NEW CALEDONIA'),
    (152, 'NEW ZEALAND'),
    (153, 'NICARAGUA'),
    (154, 'NIGER'),
    (155, 'NIGERIA'),
    (156, 'NIUE'),
    (157, 'NORFOLK ISLAND'),
    (158, 'NORTHERN MARIANA ISLANDS'),
    (159, 'NORWAY'),
    (160, 'OMAN'),
    (161, 'PAKISTAN'),
    (162, 'PALAU'),
    (163, 'PALESTINIAN TERRITORY, OCCUPIED'),
    (164, 'PANAMA'),
    (165, 'PAPUA NEW GUINEA'),
    (166, 'PARAGUAY'),
    (167, 'PERU'),
    (168, 'PHILIPPINES'),
    (169, 'PITCAIRN'),
    (170, 'POLAND'),
    (171, 'PORTUGAL'),
    (172, 'PUERTO RICO'),
    (173, 'QATAR'),
    (174, 'RÃ‰UNION'),
    (175, 'ROMANIA'),
    (176, 'RUSSIAN FEDERATION'),
    (178, 'RWANDA'),
    (179, 'SAINT HELENA'),
    (180, 'SAINT KITTS AND NEVIS'),
    (181, 'SAINT LUCIA'),
    (182, 'SAINT PIERRE AND MIQUELON'),
    (183, 'SAINT VINCENT AND THE GRENADINES'),
    (184, 'SAMOA'),
    (185, 'SAN MARINO'),
    (186, 'SAO TOME AND PRINCIPE'),
    (187, 'SAUDI ARABIA'),
    (188, 'SENEGAL'),
    (189, 'SERBIA AND MONTENEGRO'),
    (190, 'SEYCHELLES'),
    (191, 'SIERRA LEONE'),
    (192, 'SINGAPORE'),
    (193, 'SLOVAKIA'),
    (194, 'SLOVENIA'),
    (195, 'SOLOMON ISLANDS'),
    (196, 'SOMALIA'),
    (197, 'SOUTH AFRICA'),
    (198, 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS'),
    (199, 'SPAIN'),
    (200, 'SRI LANKA'),
    (201, 'SUDAN'),
    (202, 'SURINAME'),
    (203, 'SVALBARD AND JAN MAYEN'),
    (204, 'SWAZILAND'),
    (205, 'SWEDEN'),
    (206, 'SWITZERLAND'),
    (207, 'SYRIAN ARAB REPUBLIC'),
    (208, 'TAIWAN, PROVINCE OF CHINA'),
    (209, 'TAJIKISTAN'),
    (210, 'TANZANIA, UNITED REPUBLIC OF'),
    (211, 'THAILAND'),
    (212, 'TIMOR'),
    (213, 'TOGO'),
    (214, 'TOKELAU'),
    (215, 'TONGA'),
    (216, 'TRINIDAD AND TOBAGO'),
    (217, 'TUNISIA'),
    (218, 'TURKEY'),
    (219, 'TURKMENISTAN'),
    (220, 'TURKS AND CAICOS ISLANDS'),
    (221, 'TUVALU'),
    (222, 'UGANDA'),
    (223, 'UKRAINE'),
    (224, 'UNITED ARAB EMIRATES'),
    (225, 'UNITED KINGDOM'),
    (226, 'UNITED STATES'),
    (227, 'UNITED STATES MINOR OUTLYING ISLANDS'),
    (228, 'URUGUAY'),
    (229, 'UZBEKISTAN'),
    (230, 'VANUATU'),
    (231, 'VIET NAM'),
    (232, 'VIRGIN ISLANDS, BRITISH'),
    (233, 'VIRGIN ISLANDS, U.S.'),
    (234, 'WALLIS AND FUTUNA'),
    (235, 'WESTERN SAHARA'),
    (236, 'YEMEN'),
    (237, 'ZIMBABWE')
)


BOARD_NAME = {
        '1':[
            "Andhra Pradesh Board of Intermediate Education,  Hyderabad",
            "Andhra Pradesh Board of Secondary Education, Hyderabad",
            "Andhra Pradesh Open School Society, SCERT Campus, Hyderabad"
        ],
        '2':[
            "Assam Higher Secondary Education Council, Bamunimaidan, Guwahati",
            "Assam Board of Secondary Education, Guwahati"
        ],
        '3':[
            "Bihar Intermediate Education Council, Patna",
            "Bihar School Examination Board, Patna",
            "Bihar Sanskrit Shiksha Board, Patna"
        ],
        '4':[
            "Chhatisgarh Board of Secondary Education, Raipur"
        ],
        '5':[
            "Goa Board of Secondary & Higher Secondary Education, Goa"
        ],
        '6':[
            "Gujarat Secondary & Higher Secondary Education Board, Gandhi Nagar"
        ],
        '7':[
            "Haryana Board of Education, Hansi Road, Bhiwani",
            "Haryana Open School, Bhiwani"
        ],
        '8':[
            "Himachal Pradesh Board of School Education, Dharamshala"
        ],
        '9':[
            "J&K State Board of School Education, Jammu",
            "J&K State Open School, Srinagar"
        ],
        '10':[
            "Jharkhand Academic Council, Ranchi"
        ],
        '11':[
            "Karnataka Board of the Pre-University Education, Bangalore",
            "Karnataka Secondary Education Examination Borad, Bangalore",
            "Karnataka Open School, J.S.S. Maha Vidya Peeth, Mysore"
        ],
        '12':[
            "Kerala Board of Public Examinations, Pareeksha  Bhawan, Thiruvananthpuram",
            "Kerala Board of Higher Secondary Education, Thiruvananthapuram",
            "Kerala State Open School, Thiruvananthapuram"
        ],
        '13':[
            "Maharashtra State Board of Secondary and Higher Secondary Education, Pune"
        ],
        '14':[
            "Madhya Pradesh Board of Secondary Education, Bhopal",
            "M.P. State Open School, Bhopal"
        ],
        '15':[
            "Manipur Council of Higher Secondary Education, Imphal",
            "Manipur Board of Secondary Education, Imphal"
        ],
        '16':[
            "Meghalaya Board of School Education, Meghalaya"
        ],
        '17':[
            "Mizoram Board of School Education Chaltlan, Aizawl"
        ],
        '18':[
            "Nagaland Board of School Education, Kohima"
        ],
        '19':[
            "Orissa Council of Higher Secondary Education Bhubaneswar",
            "Orissa Board of Secondary Education, Cuttack"
        ],
        '20':[
            "Punjab School Education Board, Mohali"
        ],
        '21':[
            "Rajasthan Board of Secondary Education, Ajmer",
            "Rajasthan State Open School, Jaipur"
        ],
        '22':[
            "Tamil Nadu Board of Secondary Education, Chennai",
            "Tamil Nadu Board of Higher Secondary Education, Chennai"
        ],
        '23':[
            "Tripura Board of Secondary Education, Agartala, Tripura West"
        ],
        '24':[
            "U.P. Board of High School & Intermediate Education, Allahabad"
        ],
        '25':[
            "Uttranchal Shiksha Evm Pariksha Parishad, Ram Nagar, Nainital"
        ],
        '26':[
            "West Bengal Board of Secondary Education, Calcutta",
            "West Bengal Council of Higher Secondary Education, Calcutta",
            "Rabindra Mukta Vidyalaya (W.B. State Open School)",
            "West Bengal Board of Madarsa Education"
        ],
        '27':[
            "National Institute of Open Schooling (formarly National Open School), New Delhi",
            "Central Board of Secondary Education, Delhi",
            "Council for Indian School Certificate Examinations, New Delhi"
        ],
        '28':[
            "Rashtriya Sanskrit Sansthan, New Delhi",
            "Gurukul Kangri Vishwavidyalaya, Haridwar",
            "Directorate of Army Education, New Delhi",
            "Aligarh Muslim University, Aligarh.",
            "Jamia Miliya Hamdard University",
            "Banasthali Vidyapith, Banasthali, Rajasthan",
            "Jamia Millia Islamia, New Delhi",
            "IGCSE Programme from University of Cambridge, International Exam",
            "Any recognizd Board of foreign countries"
        ]
        }

STATE_UT = ((1, "Andhra Pradesh"), (2, "Assam"), (3, "Bihar"), (4, "Chhattisgarh"), (5, "Goa"), (6, "Gujarat"), (7, "Haryana"), (8, "Himachal Pradesh"), (9, "Jammu and Kashmir"), (10, "Jharkhand"), (11, "Karnataka"), (12, "Kerala"), (13, "Maharashtra"), (14, "Madhya Pradesh"), (15, "Manipur"), (16, "Meghalaya"), (17, "Mizoram"), (18, "Nagaland"), (19, "Odisha"), (20, "Punjab"), (21, "Rajasthan"), (22, "Tamil Nadu"), (23, "Tripura"), (24, "Uttar Pradesh"), (25, "Uttarakhand"), (26, "West Bengal"), (27, "All India Boards"), (28, "OTHER INSTITUTES RECOGNISED FOR SECONDARY LEVEL"))